# Site settings
author: Kenneth Neylon
title: My Coding Journey
header-img: img/home-bg.png
email: kenneth_neylon@hotmail.com
copyright_name: Kenneth Neylon
description: > # this means to ignore newlines until "baseurl:"
  New career
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kpneylon

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
